import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import * as ImagePicker from 'expo-image-picker';
import * as Sharing from 'expo-sharing';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useRef, useState } from 'react';
import { Image, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { captureRef } from 'react-native-view-shot';
import { clubCommunityApi, type ClubActivityCard } from '@/api/endpoints';
import { prepareImage } from '@/api/upload';
import { PaperScreen, SubHeader } from '@/components/collage';
import { Button, Card, Loading, formatClock } from '@/components/ui';
import { spacing, typeScale, useTheme } from '@/theme';

const STICKERS=['📚','✨','☕','🔥','💯','🌿','❤️','⭐','🎉','📝'];
export default function ClubActivityScreen(){const {id}=useLocalSearchParams<{id:string}>();const clubId=Number(id);const router=useRouter();const qc=useQueryClient();const {colors}=useTheme();const [now,setNow]=useState(Date.now());const [editing,setEditing]=useState<ClubActivityCard|null>(null);const [caption,setCaption]=useState('');const [stickers,setStickers]=useState<string[]>([]);const [photo,setPhoto]=useState<ImagePicker.ImagePickerAsset|null>(null);const [sharing,setSharing]=useState(false);const cardRef=useRef<View>(null);
 const current=useQuery({queryKey:['clubActivity',clubId,'current'],queryFn:()=>clubCommunityApi.currentActivity(clubId)});const cards=useQuery({queryKey:['clubActivity',clubId,'cards'],queryFn:()=>clubCommunityApi.activityCards(clubId)});const refresh=()=>qc.invalidateQueries({queryKey:['clubActivity',clubId]});
 useEffect(()=>{if(!current.data)return;const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[current.data]);
 const start=useMutation({mutationFn:()=>clubCommunityApi.startActivity(clubId),onSuccess:refresh});const end=useMutation({mutationFn:()=>clubCommunityApi.endActivity(clubId),onSuccess:c=>{setEditing(c);refresh();}});
 const save=useMutation({mutationFn:async()=>{if(!editing)throw new Error();const form=photo?await prepareImage(photo):new FormData();form.append('caption',caption);form.append('decorationsJson',JSON.stringify(stickers));return clubCommunityApi.decorateActivityCard(clubId,editing.id,form)},onSuccess:c=>{setEditing(c);setPhoto(null);refresh();}});
 const pick=async()=>{const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted)return;const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:1});if(!r.canceled)setPhoto(r.assets[0]);};
 const share=async()=>{if(!cardRef.current)return;setSharing(true);try{const uri=await captureRef(cardRef,{format:'png',quality:1,result:Platform.OS==='web'?'data-uri':'tmpfile',width:1080,height:1350});if(Platform.OS==='web'){const a=document.createElement('a');a.href=uri;a.download=`bookey-club-${editing?.id}.png`;a.click();}else if(await Sharing.isAvailableAsync())await Sharing.shareAsync(uri,{mimeType:'image/png',dialogTitle:'모임 기록 카드 저장·공유'});}finally{setSharing(false)}};
 if(current.isLoading)return <PaperScreen><SubHeader category="모임 스탑워치" onBack={()=>router.back()}/><Loading/></PaperScreen>;const elapsed=current.data?Math.max(0,Math.floor((now-new Date(current.data.startedAt).getTime())/1000)):0;const card=editing;const shownPhoto=photo?.uri??card?.photoUrl;
 return <PaperScreen><SubHeader category="모임 스탑워치" onBack={()=>router.back()}/><ScrollView contentContainerStyle={s.container}>{card?<><View ref={cardRef} collapsable={false} style={[s.resultCard,{backgroundColor:colors.surface}]}>{shownPhoto?<Image source={{uri:shownPhoto}} style={s.photo}/>:<View style={[s.photo,{backgroundColor:colors.paperAlt}]}/>}<Text style={s.stickerLayer}>{stickers.join('  ')}</Text><Text style={[s.cardTitle,{color:colors.text}]}>오늘의 모임 기록</Text><Text style={[s.duration,{color:colors.accent}]}>{formatClock(card.durationSec)}</Text><Text style={[typeScale.body,{color:colors.text}]}>{caption||'함께여서 더 오래 집중한 시간'}</Text><Text style={[typeScale.caption,{color:colors.textMuted}]}>@{card.nickname} · BOOKEY CLUB</Text></View><Card><TextInput value={caption} onChangeText={setCaption} maxLength={500} placeholder="기록 카드에 남길 한마디" placeholderTextColor={colors.textFaint} style={[s.input,{color:colors.text,borderColor:colors.lineStrong}]}/><View style={s.stickers}>{STICKERS.map(x=><Pressable key={x} onPress={()=>setStickers(v=>v.length<8?[...v,x]:v)}><Text style={s.sticker}>{x}</Text></Pressable>)}</View><View style={s.actions}><Button label="스티커 지우기" size="sm" variant="ghost" onPress={()=>setStickers([])}/><Button label="사진 첨부" size="sm" variant="outline" onPress={pick}/></View><Button label="꾸미기 저장" onPress={()=>save.mutate()} loading={save.isPending}/><Button label="PNG 저장·공유" variant="outline" onPress={share} loading={sharing}/><Button label="완료" variant="ghost" onPress={()=>{setEditing(null);setCaption('');setStickers([])}}/></Card></>:<><Card><Text style={[s.timer,{color:colors.text}]}>{formatClock(elapsed)}</Text><Text style={[typeScale.body,{color:colors.textMuted,textAlign:'center'}]}>{current.data?'모임 집중 시간을 기록하고 있어요.':'모임 사람들과 함께한 시간을 기록해보세요.'}</Text><Button label={current.data?'기록 종료':'스탑워치 시작'} variant={current.data?'danger':'primary'} onPress={()=>current.data?end.mutate():start.mutate()} loading={start.isPending||end.isPending}/></Card><Text style={[s.section,{color:colors.text}]}>최근 모임 기록</Text>{(cards.data??[]).map(c=><Pressable key={c.id} onPress={()=>{setEditing(c);setCaption(c.caption??'');try{setStickers(JSON.parse(c.decorationsJson))}catch{setStickers([])}}}><Card><Text style={[typeScale.bodyStrong,{color:colors.text}]}>{c.nickname} · {formatClock(c.durationSec)}</Text><Text style={[typeScale.caption,{color:colors.textMuted}]}>{c.caption||'꾸미지 않은 기록 카드'}</Text></Card></Pressable>)}</>}</ScrollView></PaperScreen>}
const s=StyleSheet.create({container:{padding:spacing.lg,gap:spacing.md,paddingBottom:80},timer:{fontSize:52,fontWeight:'800',textAlign:'center',fontVariant:['tabular-nums']},section:{...typeScale.title,marginTop:spacing.md},resultCard:{height:500,borderRadius:24,padding:24,overflow:'hidden',justifyContent:'flex-end',gap:8},photo:{position:'absolute',top:0,left:0,right:0,width:'100%',height:'62%',opacity:.78},stickerLayer:{position:'absolute',top:30,left:20,right:20,fontSize:36,textAlign:'center'},cardTitle:{fontSize:27,fontWeight:'800'},duration:{fontSize:44,fontWeight:'900'},input:{borderWidth:1,borderRadius:12,padding:12},stickers:{flexDirection:'row',flexWrap:'wrap',gap:12,marginVertical:spacing.md},sticker:{fontSize:30},actions:{flexDirection:'row',gap:spacing.sm,marginBottom:spacing.md}});
