import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { clubCommunityApi } from '@/api/endpoints';
import { PaperScreen, SubHeader } from '@/components/collage';
import { Button, Card, Loading } from '@/components/ui';
import { spacing, typeScale, useTheme } from '@/theme';

export default function ClubChatScreen(){const {id}=useLocalSearchParams<{id:string}>();const clubId=Number(id);const router=useRouter();const qc=useQueryClient();const {colors}=useTheme();const [draft,setDraft]=useState('');
 const state=useQuery({queryKey:['clubChat',clubId,'state'],queryFn:()=>clubCommunityApi.chatState(clubId)});
 const pages=useInfiniteQuery({queryKey:['clubChat',clubId,'messages'],queryFn:({pageParam})=>clubCommunityApi.chatMessages(clubId,pageParam),initialPageParam:undefined as number|undefined,getNextPageParam:p=>p.nextBeforeId,enabled:state.data?.unlocked===true,refetchInterval:4000});
 const unlock=useMutation({mutationFn:()=>clubCommunityApi.unlockChat(clubId),onSuccess:()=>{qc.invalidateQueries({queryKey:['clubChat',clubId]});}});
 const send=useMutation({mutationFn:(body:string)=>clubCommunityApi.sendChat(clubId,body),onSuccess:()=>{setDraft('');qc.invalidateQueries({queryKey:['clubChat',clubId]});}});
 const items=useMemo(()=>pages.data?.pages.flatMap(p=>p.messages)??[],[pages.data]); if(state.isLoading)return <PaperScreen><SubHeader category="모임 채팅" onBack={()=>router.back()}/><Loading/></PaperScreen>;
 if(!state.data?.unlocked)return <PaperScreen><SubHeader category="모임 채팅" onBack={()=>router.back()}/><View style={s.lock}><Card><Text style={[s.title,{color:colors.text}]}>새 메시지 {state.data?.unreadCount??0}개</Text><Text style={[typeScale.body,{color:colors.textMuted}]}>책갈피 {state.data?.unlockCost??2}개로 채팅을 열면 이전 대화 전체를 읽고 메시지를 보낼 수 있어요.</Text><Text style={[typeScale.caption,{color:colors.textFaint}]}>현재 책갈피 {state.data?.bookmarkBalance??0}개 · 해제 후 환불되지 않아요.</Text><Button label={unlock.isPending?'여는 중…':`책갈피 ${state.data?.unlockCost??2}개로 열기`} onPress={()=>unlock.mutate()} disabled={unlock.isPending}/>{unlock.error?<Text style={{color:colors.danger}}>책갈피가 부족하거나 채팅을 열 수 없습니다.</Text>:null}</Card></View></PaperScreen>;
 return <PaperScreen><SubHeader category="모임 채팅" onBack={()=>router.back()}/><FlatList style={{flex:1}} inverted data={items} keyExtractor={m=>String(m.id)} contentContainerStyle={s.list} onEndReached={()=>pages.hasNextPage&&pages.fetchNextPage()} renderItem={({item})=><View style={[s.row,item.mine&&{justifyContent:'flex-end'}]}><View style={[s.bubble,{backgroundColor:item.mine?colors.accent:colors.surface}]}>{!item.mine?<Text style={[typeScale.caption,{color:colors.textFaint}]}>{item.senderNickname}</Text>:null}<Text style={[typeScale.body,{color:item.mine?colors.onAccent:colors.text}]}>{item.body}</Text></View></View>}/><View style={s.input}><TextInput value={draft} onChangeText={setDraft} placeholder="메시지 보내기" placeholderTextColor={colors.textFaint} multiline maxLength={1000} style={[s.textInput,{color:colors.text,borderColor:colors.lineStrong}]}/><Pressable onPress={()=>{const b=draft.trim();if(b)send.mutate(b)}} disabled={!draft.trim()||send.isPending} style={[s.send,{backgroundColor:colors.accent}]}>{send.isPending?<ActivityIndicator/>:<Text style={{color:colors.onAccent}}>↑</Text>}</Pressable></View></PaperScreen>}
const s=StyleSheet.create({lock:{flex:1,justifyContent:'center',padding:spacing.lg},title:{...typeScale.title,marginBottom:spacing.md},list:{padding:spacing.lg,gap:spacing.sm},row:{flexDirection:'row'},bubble:{maxWidth:'80%',padding:spacing.md,borderRadius:16,gap:4},input:{flexDirection:'row',padding:spacing.md,gap:spacing.sm,alignItems:'flex-end'},textInput:{flex:1,borderWidth:1,borderRadius:14,padding:12,maxHeight:100},send:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center'}});
