import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Redirect, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { clubCommunityApi } from '@/api/endpoints';
import { Button, Card, Loading } from '@/components/ui';
import { radius, spacing, typeScale, useTheme } from '@/theme';

export function ClubChatBody(){const {id}=useLocalSearchParams<{id:string}>();const clubId=Number(id);const qc=useQueryClient();const {colors}=useTheme();const [draft,setDraft]=useState('');const [showGift,setShowGift]=useState(false);
 const state=useQuery({queryKey:['clubChat',clubId,'state'],queryFn:()=>clubCommunityApi.chatState(clubId)});
 const pages=useInfiniteQuery({queryKey:['clubChat',clubId,'messages'],queryFn:({pageParam})=>clubCommunityApi.chatMessages(clubId,pageParam),initialPageParam:undefined as number|undefined,getNextPageParam:p=>p.nextBeforeId,enabled:state.data?.unlocked===true,refetchInterval:4000});
 const candidates=useQuery({queryKey:['clubChat',clubId,'giftCandidates'],queryFn:()=>clubCommunityApi.giftCandidates(clubId),enabled:showGift});
 const refresh=()=>qc.invalidateQueries({queryKey:['clubChat',clubId]});
 const unlock=useMutation({mutationFn:()=>clubCommunityApi.unlockChat(clubId),onSuccess:refresh});
 const gift=useMutation({mutationFn:(userId:number)=>clubCommunityApi.giftChat(clubId,userId),onSuccess:refresh});
 const send=useMutation({mutationFn:(body:string)=>clubCommunityApi.sendChat(clubId,body),onSuccess:()=>{setDraft('');refresh();}});
 const items=useMemo(()=>pages.data?.pages.flatMap(p=>p.messages)??[],[pages.data]);
 const giftModal=<Modal visible={showGift} transparent animationType="slide" onRequestClose={()=>setShowGift(false)}><View style={s.modalBackdrop}><Card><Text style={[s.title,{color:colors.text}]}>채팅 이용권 선물</Text><Text style={[typeScale.caption,{color:colors.textMuted}]}>내 책갈피 2개로 선택한 멤버의 채팅을 열어줘요.</Text><ScrollView style={{maxHeight:320}}>{(candidates.data??[]).map(c=><View key={c.userId} style={s.giftRow}><Text style={[typeScale.body,{color:colors.text}]}>{c.nickname}</Text><Button size="sm" variant={c.unlocked?'ghost':'outline'} label={c.unlocked?'이용 중':'2개 선물'} disabled={c.unlocked||gift.isPending} onPress={()=>gift.mutate(c.userId)}/></View>)}</ScrollView>{gift.error?<Text style={{color:colors.danger}}>책갈피가 부족하거나 선물할 수 없어요.</Text>:null}<Button label="닫기" variant="ghost" onPress={()=>setShowGift(false)}/></Card></View></Modal>;
 if(state.isLoading)return <Loading/>;
 const header=<View style={s.giftBar}><Button label="선물" size="sm" variant="ghost" onPress={()=>setShowGift(true)}/></View>;
 if(!state.data?.unlocked)return <View style={s.bodyFill}>{header}{giftModal}<View style={s.lock}><Card><Text style={[s.title,{color:colors.text}]}>새 메시지 {state.data?.unreadCount??0}개</Text><Text style={[typeScale.body,{color:colors.textMuted}]}>책갈피 {state.data?.unlockCost??2}개로 채팅을 열면 이전 대화 전체를 읽고 메시지를 보낼 수 있어요.</Text><Text style={[typeScale.caption,{color:colors.textFaint}]}>현재 책갈피 {state.data?.bookmarkBalance??0}개 · 해제 후 환불되지 않아요.</Text><Button label={unlock.isPending?'여는 중…':`책갈피 ${state.data?.unlockCost??2}개로 열기`} onPress={()=>unlock.mutate()} disabled={unlock.isPending}/>{unlock.error?<Text style={{color:colors.danger}}>책갈피가 부족하거나 채팅을 열 수 없습니다.</Text>:null}</Card></View></View>;
 return <View style={s.bodyFill}>{header}{giftModal}<FlatList style={{flex:1}} inverted data={items} keyExtractor={m=>String(m.id)} contentContainerStyle={s.list} onEndReached={()=>pages.hasNextPage&&pages.fetchNextPage()} renderItem={({item})=><View style={[s.row,item.mine&&{justifyContent:'flex-end'}]}><View style={[s.bubble,{backgroundColor:item.mine?colors.accent:colors.surface}]}>{!item.mine?<Text style={[typeScale.caption,{color:colors.textFaint}]}>{item.senderNickname}</Text>:null}<Text style={[typeScale.body,{color:item.mine?colors.onAccent:colors.text}]}>{item.body}</Text></View></View>}/><View style={s.input}><TextInput value={draft} onChangeText={setDraft} placeholder="메시지 보내기" placeholderTextColor={colors.textFaint} multiline maxLength={1000} style={[s.textInput,{color:colors.text,borderColor:colors.lineStrong}]}/><Pressable onPress={()=>{const b=draft.trim();if(b)send.mutate(b)}} disabled={!draft.trim()||send.isPending} style={[s.send,{backgroundColor:colors.accent}]}>{send.isPending?<ActivityIndicator/>:<Text style={{color:colors.onAccent}}>↑</Text>}</Pressable></View></View>}
const s=StyleSheet.create({bodyFill:{flex:1},giftBar:{flexDirection:'row',justifyContent:'flex-end',paddingHorizontal:spacing.lg,paddingTop:spacing.xs},lock:{flex:1,justifyContent:'center',padding:spacing.lg},title:{...typeScale.title,marginBottom:spacing.md},list:{padding:spacing.lg,gap:spacing.sm},row:{flexDirection:'row'},bubble:{maxWidth:'80%',padding:spacing.md,borderRadius:radius.md,gap:4},input:{flexDirection:'row',padding:spacing.md,gap:spacing.sm,alignItems:'flex-end'},textInput:{flex:1,borderWidth:1,borderRadius:radius.sm,padding:12,maxHeight:100},send:{width:44,height:44,borderRadius:radius.sm,alignItems:'center',justifyContent:'center'},modalBackdrop:{flex:1,justifyContent:'center',padding:spacing.lg,backgroundColor:'rgba(0,0,0,.45)'},giftRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:spacing.sm}});
/** 딥링크 호환 — 채팅은 이제 모임 홈의 탭이다. */
export default function ClubChatRoute(){const {id}=useLocalSearchParams<{id:string}>();return <Redirect href={{pathname:'/club/[id]',params:{id,tab:'chat'}}}/>;}
