import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { Linking, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { clubCommunityApi, type ClubMeetingInput } from '@/api/endpoints';
import { PaperScreen, SubHeader } from '@/components/collage';
import { Button, Card, Loading } from '@/components/ui';
import { spacing, typeScale, useTheme } from '@/theme';

export default function ClubMeetingsScreen(){const {id,host}=useLocalSearchParams<{id:string;host?:string}>();const clubId=Number(id);const isHost=host==='1';const router=useRouter();const qc=useQueryClient();const {colors}=useTheme();const [open,setOpen]=useState(false);const [invalidDate,setInvalidDate]=useState(false);const [form,setForm]=useState({title:'',description:'',startsAt:'',placeName:'',address:'',mapUrl:''});const list=useQuery({queryKey:['clubMeetings',clubId],queryFn:()=>clubCommunityApi.meetings(clubId)});const refresh=()=>qc.invalidateQueries({queryKey:['clubMeetings',clubId]});const create=useMutation({mutationFn:(b:ClubMeetingInput)=>clubCommunityApi.createMeeting(clubId,b),onSuccess:()=>{setOpen(false);setForm({title:'',description:'',startsAt:'',placeName:'',address:'',mapUrl:''});refresh();}});const attend=useMutation({mutationFn:({mid,on}:{mid:number;on:boolean})=>on?clubCommunityApi.unattend(clubId,mid):clubCommunityApi.attend(clubId,mid),onSuccess:refresh});const cancel=useMutation({mutationFn:(mid:number)=>clubCommunityApi.cancelMeeting(clubId,mid),onSuccess:refresh});
 const submit=()=>{const date=new Date(form.startsAt);if(Number.isNaN(date.getTime())){setInvalidDate(true);return;}setInvalidDate(false);create.mutate({...form,mapUrl:form.mapUrl||undefined,startsAt:date.toISOString()});}; const map=(m:{mapUrl?:string;latitude?:number;longitude?:number;address:string})=>{const url=m.mapUrl??(m.latitude!=null&&m.longitude!=null?`https://maps.google.com/?q=${m.latitude},${m.longitude}`:`https://maps.google.com/?q=${encodeURIComponent(m.address)}`);void Linking.openURL(url)};
 return <PaperScreen><SubHeader category="모임 약속" onBack={()=>router.back()} right={isHost?<Button label={open?'닫기':'약속 만들기'} size="sm" variant="ghost" onPress={()=>setOpen(v=>!v)}/>:undefined}/><ScrollView contentContainerStyle={s.container}>{open?<Card><Text style={[s.heading,{color:colors.text}]}>새 약속</Text>{(['title','startsAt','placeName','address','mapUrl','description'] as const).map(k=><TextInput key={k} value={form[k]} onChangeText={v=>setForm(f=>({...f,[k]:v}))} placeholder={({title:'약속 제목',startsAt:'일시 예: 2026-10-03 14:00',placeName:'장소명',address:'주소',mapUrl:'지도 공유 링크 (선택)',description:'설명 (선택)'})[k]} placeholderTextColor={colors.textFaint} multiline={k==='description'} style={[s.input,{color:colors.text,borderColor:colors.lineStrong}]}/>)}<Button label={create.isPending?'등록 중…':'약속 열기'} onPress={submit} disabled={!form.title||!form.startsAt||!form.placeName||!form.address||create.isPending}/>{invalidDate||create.error?<Text style={{color:colors.danger}}>일시와 입력 내용을 확인해 주세요.</Text>:null}</Card>:null}{list.isLoading?<Loading/>:(list.data??[]).length===0?<Text style={[typeScale.body,{color:colors.textMuted}]}>아직 열린 약속이 없어요.</Text>:(list.data??[]).map(m=><Card key={m.id}><View style={s.head}><Text style={[s.heading,{color:colors.text}]}>{m.title}</Text><Text style={[typeScale.caption,{color:m.status==='OPEN'?colors.accent:colors.danger}]}>{m.status==='OPEN'?'모집 중':'취소됨'}</Text></View><Text style={[typeScale.body,{color:colors.text}]}>{new Date(m.startsAt).toLocaleString('ko-KR')}</Text><Text style={[typeScale.body,{color:colors.textMuted}]}>{m.placeName} · {m.address}</Text>{m.description?<Text style={[typeScale.caption,{color:colors.textMuted}]}>{m.description}</Text>:null}<Text style={[typeScale.caption,{color:colors.textFaint}]}>참여 {m.attendeeCount}명{m.attendeeNicknames.length?` · ${m.attendeeNicknames.join(', ')}`:''}</Text><View style={s.actions}><Button label="지도 보기" variant="outline" size="sm" onPress={()=>map(m)}/>{m.status==='OPEN'?<Button label={m.attending?'참여 취소':'참여하기'} size="sm" variant={m.attending?'ghost':'primary'} onPress={()=>attend.mutate({mid:m.id,on:m.attending})}/>:null}{isHost&&m.status==='OPEN'?<Button label="약속 취소" variant="ghost" size="sm" onPress={()=>cancel.mutate(m.id)}/>:null}</View></Card>)}</ScrollView></PaperScreen>}
const s=StyleSheet.create({container:{padding:spacing.lg,gap:spacing.md},heading:{...typeScale.bodyStrong},head:{flexDirection:'row',justifyContent:'space-between',gap:spacing.md},input:{borderWidth:1,borderRadius:12,padding:12,marginBottom:spacing.sm},actions:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm,marginTop:spacing.sm}});
