import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { clubCommunityApi, type ClubMeetingInput, type ClubPlace } from '@/api/endpoints';
import { PaperScreen, SubHeader } from '@/components/collage';
import { PlaceMap } from '@/components/club/PlaceMap';
import { Button, Card, Loading } from '@/components/ui';
import { spacing, typeScale, useTheme } from '@/theme';

const emptyForm = { title: '', description: '', startsAt: '', placeName: '', address: '', mapUrl: '', latitude: undefined as number|undefined, longitude: undefined as number|undefined };

export default function ClubMeetingsScreen() {
  const { id, host } = useLocalSearchParams<{ id: string; host?: string }>();
  const clubId = Number(id); const isHost = host === '1'; const router = useRouter(); const qc = useQueryClient(); const { colors } = useTheme();
  const [open, setOpen] = useState(false); const [invalidDate, setInvalidDate] = useState(false); const [form, setForm] = useState(emptyForm); const [placeQuery, setPlaceQuery] = useState(''); const [debouncedQuery, setDebouncedQuery] = useState('');
  useEffect(() => { const timer = setTimeout(() => setDebouncedQuery(placeQuery.trim()), 350); return () => clearTimeout(timer); }, [placeQuery]);
  const list = useQuery({ queryKey: ['clubMeetings', clubId], queryFn: () => clubCommunityApi.meetings(clubId) });
  const places = useQuery({ queryKey: ['clubPlaces', clubId, debouncedQuery], queryFn: () => clubCommunityApi.searchPlaces(clubId, debouncedQuery), enabled: debouncedQuery.length >= 2 });
  const refresh = () => qc.invalidateQueries({ queryKey: ['clubMeetings', clubId] });
  const create = useMutation({ mutationFn: (body: ClubMeetingInput) => clubCommunityApi.createMeeting(clubId, body), onSuccess: () => { setOpen(false); setForm(emptyForm); setPlaceQuery(''); refresh(); } });
  const attend = useMutation({ mutationFn: ({ mid, on }: { mid: number; on: boolean }) => on ? clubCommunityApi.unattend(clubId, mid) : clubCommunityApi.attend(clubId, mid), onSuccess: refresh });
  const cancel = useMutation({ mutationFn: (mid: number) => clubCommunityApi.cancelMeeting(clubId, mid), onSuccess: refresh });
  const selectPlace = (place: ClubPlace) => { setForm(f => ({ ...f, placeName: place.name, address: place.roadAddress || place.address, latitude: place.latitude, longitude: place.longitude, mapUrl: place.mapUrl ?? '' })); setPlaceQuery(place.name); setDebouncedQuery(''); };
  const submit = () => { const date = new Date(form.startsAt); if (Number.isNaN(date.getTime())) { setInvalidDate(true); return; } setInvalidDate(false); create.mutate({ ...form, mapUrl: form.mapUrl || undefined, startsAt: date.toISOString() }); };
  const openMap = (m: { mapUrl?: string; latitude?: number; longitude?: number; address: string }) => {
    const query = m.latitude != null && m.longitude != null ? `${m.latitude},${m.longitude}` : m.address;
    void Linking.openURL(m.mapUrl ?? `https://maps.google.com/?q=${encodeURIComponent(query)}`);
  };
  return <PaperScreen><SubHeader category="모임 약속" onBack={() => router.back()} right={isHost ? <Button label={open ? '닫기' : '약속 만들기'} size="sm" variant="ghost" onPress={() => setOpen(v => !v)} /> : undefined}/><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled">
    {open ? <Card><Text style={[s.heading,{color:colors.text}]}>새 약속</Text><TextInput value={form.title} onChangeText={title=>setForm(f=>({...f,title}))} placeholder="약속 제목" placeholderTextColor={colors.textFaint} style={[s.input,{color:colors.text,borderColor:colors.lineStrong}]}/><TextInput value={form.startsAt} onChangeText={startsAt=>setForm(f=>({...f,startsAt}))} placeholder="일시 예: 2026-10-03 14:00" placeholderTextColor={colors.textFaint} style={[s.input,{color:colors.text,borderColor:colors.lineStrong}]}/><Text style={[typeScale.bodyStrong,{color:colors.text}]}>장소 검색</Text><TextInput value={placeQuery} onChangeText={setPlaceQuery} placeholder="장소명이나 주소를 검색하세요" placeholderTextColor={colors.textFaint} style={[s.input,{color:colors.text,borderColor:colors.lineStrong}]}/>{places.isFetching?<Loading/>:(places.data??[]).map(p=><Pressable key={p.id} onPress={()=>selectPlace(p)} style={[s.placeRow,{borderBottomColor:colors.line}]}><Text style={[typeScale.bodyStrong,{color:colors.text}]}>{p.name}</Text><Text style={[typeScale.caption,{color:colors.textMuted}]}>{p.roadAddress||p.address}</Text></Pressable>)}{form.latitude!=null?<><PlaceMap latitude={form.latitude} longitude={form.longitude}/><Text style={[typeScale.caption,{color:colors.textMuted}]}>{form.placeName} · {form.address}</Text></>:null}<TextInput value={form.description} onChangeText={description=>setForm(f=>({...f,description}))} placeholder="설명 (선택)" placeholderTextColor={colors.textFaint} multiline style={[s.input,{color:colors.text,borderColor:colors.lineStrong}]}/><Button label={create.isPending?'등록 중…':'약속 열기'} onPress={submit} disabled={!form.title||!form.startsAt||!form.placeName||!form.address||create.isPending}/>{invalidDate||create.error?<Text style={{color:colors.danger}}>일시와 입력 내용을 확인해 주세요.</Text>:null}</Card>:null}
    {list.isLoading?<Loading/>:(list.data??[]).length===0?<Text style={[typeScale.body,{color:colors.textMuted}]}>아직 열린 약속이 없어요.</Text>:(list.data??[]).map(m=><Card key={m.id}><View style={s.head}><Text style={[s.heading,{color:colors.text}]}>{m.title}</Text><Text style={[typeScale.caption,{color:m.status==='OPEN'?colors.accent:colors.danger}]}>{m.status==='OPEN'?'모집 중':'취소됨'}</Text></View><Text style={[typeScale.body,{color:colors.text}]}>{new Date(m.startsAt).toLocaleString('ko-KR')}</Text><Text style={[typeScale.body,{color:colors.textMuted}]}>{m.placeName} · {m.address}</Text>{m.latitude!=null?<PlaceMap latitude={m.latitude} longitude={m.longitude}/>:null}{m.description?<Text style={[typeScale.caption,{color:colors.textMuted}]}>{m.description}</Text>:null}<Text style={[typeScale.caption,{color:colors.textFaint}]}>참여 {m.attendeeCount}명{m.attendeeNicknames.length?` · ${m.attendeeNicknames.join(', ')}`:''}</Text><View style={s.actions}><Button label="지도 앱에서 보기" variant="outline" size="sm" onPress={()=>openMap(m)}/>{m.status==='OPEN'?<Button label={m.attending?'참여 취소':'참여하기'} size="sm" variant={m.attending?'ghost':'primary'} onPress={()=>attend.mutate({mid:m.id,on:m.attending})}/>:null}{isHost&&m.status==='OPEN'?<Button label="약속 취소" variant="ghost" size="sm" onPress={()=>cancel.mutate(m.id)}/>:null}</View></Card>)}
  </ScrollView></PaperScreen>;
}
const s=StyleSheet.create({container:{padding:spacing.lg,gap:spacing.md},heading:{...typeScale.bodyStrong},head:{flexDirection:'row',justifyContent:'space-between',gap:spacing.md},input:{borderWidth:1,borderRadius:12,padding:12,marginBottom:spacing.sm},placeRow:{paddingVertical:spacing.sm,borderBottomWidth:1,gap:2},actions:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm,marginTop:spacing.sm}});
